export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
export const LOGIN_FORM_UNMOUNT = 'LOGIN_FORM_UNMOUNT';
export const LOGIN_FORM_INVALID = 'LOGIN_FORM_INVALID';
export const LOGIN_FORM_REQUEST = 'LOGIN_FORM_REQUEST';
export const LOGIN_FORM_ERROR = 'LOGIN_FORM_ERROR';
export const USER_IS_AUTHORIZED = 'USER_IS_AUTHORIZED';


export const FETCH_SERVERS_SUCCESS = 'FETCH_SERVERS_SUCCESS'
export const FETCH_SERVERS_FAILED = 'FETCH_SERVERS_FAILED'